### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Cuxx**
added the db backup copf function. without this the backups would remain in the old folder.

### CODE REVIEW

**Review by szafranski — COMMENTED** [review]
So your intention is that the user could have additional backup of his RH most important files INSIDE RotorHazard directory? Asking cause right now there are alredy 2 locations where those files are kept "just in case".

**Comment by Cuxx** [comment]
yes in the current rh-master they are placed there

**Comment by szafranski** [comment]
But I think I already added this - look at the line 41 of this file.

W dniu czw., 22.10.2020 o 23:22 Cuxx <notifications@github.com> napisał(a):

**Comment by Cuxx** [comment]
I don't think so. Line 41 copies only the static/user/ folder, but not the db_bkp folder. That folder is directly in the src folder (will be created by the code when you create a backup)

**Comment by szafranski** [comment]
Oh, ok. Can I just merge it? have U tested that?

W dniu pt., 23.10.2020 o 12:55 Cuxx <notifications@github.com> napisał(a):

**Comment by szafranski** [comment]
I know it is simple code addition but I just want to know if U used it already? :) Cheers!

**Comment by Cuxx** [comment]
Oh yeah I checked on both tracker. One was without the folder, and the other one with several db backups. Both worked as expected.

**Comment by szafranski** [comment]
Cool. Thanks.

**Pull request merged**
